name: Enterprise DevOps Docker Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  # JOB 1: Pengecekan Keamanan File Mentah (SCA)
  security-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Ambil Kode dari Git
      uses: actions/checkout@v4

    - name: Scan Library Mentah via Trivy
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'table'
        exit-code: '1'
        severity: 'HIGH,CRITICAL'

  # JOB 2: Memasak Docker & Menguji Keamanan Kontainer Jadi
  build-and-test-docker:
    runs-on: ubuntu-latest
    needs: security-scan # KUNCI: Nunggu sensor file mentah lolos dulu
    steps:
    - name: Ambil Kode dari Git
      uses: actions/checkout@v4

    # Perintah Bash asli untuk membangun Docker Image dari Dockerfile tadi
    - name: Build Docker Image Lokal
      run: |
        docker build -t aplikasi-saya:test .

    # SEBELUM DEPLOY: Scan kontainer jadinya, barangkali OS di dalam Dockernya ada virus
    - name: Scan Docker Image via Trivy (Asli)
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'aplikasi-saya:test' # Nama image yang di-build di atas
        format: 'table'
        exit-code: '1'                 # KETAT: Gagalkan kalau OS Dockernya bervirus!
        severity: 'HIGH,CRITICAL'

    - name: Simulasi Push & Deploy ke AWS
      run: |
        echo "Docker Image aman dan bersih dari celah keamanan!"
        echo "Siap di-push ke AWS Container Registry (ECR)."
